### ISSUE TITLE
Feature: Tab Auto-Complete

### ISSUE THREAD

**Issue by benserwa** [BeipDev/BeipMU#120]
I would like it if pressing Tab would cause the current word you're typing to auto-complete, using the most recent word in the history window that completes the current word-in-progress to quickly finish the word you're typing. This is useful for lots of reasons, such as people with hard to spell fantasy names.

**Comment by BeipDev** [comment]
How about pressing tab does a '100' or '1000' line search in your history (or also the output?) builds the list of words and makes a popup once it hits 10 choices or scans that far in the windows. I could also have it give you the 10 most popular choices for the words. This way you can visually choose vs lots of tabbing blindly?

**Comment by benserwa** [comment]
Makes sense. A specific enough search should probably only result in one particular word, so maybe just have it auto-complete right away if that's the case, and have a little pop-up to choose if there's more than one option. It'd be important for selecting one of the results to be keyboard only friendly.

**Comment by BeipDev** [comment]
Yeah, this would be keyboard friendly. I think always showing the popup is handy to be consistent, but it'd be like this:

you start typing:
bens<tab>
It pops up next to your cursor [benswerwa] (a menu with only one choice). You press enter and it replaces. Otherwise it might mess with muscle memory to do one action when there's one choice and another when there are 2+ in the menu.

My only worry is that popup menus use 'enter' to choose an item, and a second enter will then send the whole line.

**Comment by benserwa** [comment]
Perhaps you're right about the muscle memory. As for hitting enter to choose, I understand the worry, not sure what the alternative is, though. Maybe detect for enter being pressed twice in rapid succession and give a warning?

**Comment by BeipDev** [comment]
Hah, at fist I'm thinking that might be a good idea but then it'll prevent the user from doing it quickly intentionally... hmm. We can prototype it and see if it's a problem.

**Comment by benserwa** [comment]
The way this is used, I think most of the time it'll be in the middle of an input rather than right at the end, so wanting to auto-complete right into sending the input shouldn't be a common case scenario, but maybe I'm wrong.
