### ISSUE TITLE
Spawn windows as regular tabs

### ISSUE THREAD

**Issue by Tokeli** [BeipDev/BeipMU#160]
I've been checking up on BeipMU every so often for like 8+ years now, staring wistfully from my ancient decrepit SimpleMU box.

It's like watching a FERRARI roar by from your amish cart and buggy, and I've been wanting to switch for absolutely ages, but it's always been lacking one major feature from SimpleMU that I never thought to ask about.

Beip has spawn windows, but is it possible to have an option for those windows to automatically act as regular tabs, like in SimpleMU? Not as a sidebar, but shoving themself into the tab list next to their parent tab, with an input window and all.

They're fantastic for isolating pages/whispers per person, but having multiple at a time squish each other off to the side is claustrophobic, and the disconnected input box gives a weird feeling.

**Comment by BeipDev** [comment]
Haha, gotta love SimpleMU's staying power!

Hmm, have you looked at the puppet feature? Those do appear as separate tabs, and work very similarly in that you can also set a regex to decide what gets routed to their tab, and you can set a prefix to apply to anything you send from that tab.

**Comment by Tokeli** [comment]
Wow, how many years have I completely missed where this was and how it worked?! This is effectively exactly what I needed! Having to set them up per-character is a little awkward but dear god, I can finally put SimpleMU out to pasture and use the only good MU client anyone's made since.

Just wondering, but, is there a reason they require a character?

**Comment by BeipDev** [comment]
Yeah, they're probably not intuitive unless you know what you're looking for. The original idea was from puppets used on mucks, where you'd have a secondary character you control through your primary character (which is why they're objects on your character). They can connect automatically if your character connects, and log, etc.. so they're 'almost' like full characters but they operate through the primary character's connection.

You're not using characters? Or you want one to be shared across multiple characters?

Oh, and if you use Discord it's a great place to ask the silliest questions or ask how to do stuff. It's not super busy so questions get replies fast (by more than just me). Since you're just starting out you might have a lot of little random questions or even feature ideas, so don't let them go to waste!

Is this issue safe to close?

**Comment by Tokeli** [comment]
Sorry about that, I'll close it and join the Discord, thank you!
