### ISSUE TITLE
UFT Code

### ISSUE THREAD

**Issue by lordbongos** [BeipDev/BeipMU#161]
UFT8 keeps setting as the default text encoding, forcing me to have to manually reset to cp-1252 every time I log into a world.  I've been trying to find a way to just set it to se 1252 by default, but no glory in Mudville.  Anything being missed?

**Comment by BeipDev** [comment]
Aha, another bad server.. I'm putting in a workaround for the servers with this bug. What server is it? I can tell you what they're doing wrong so they can hopefully fix it.

**Comment by lordbongos** [comment]
Server is Star Wars AOA swaoa-mush.com:5500

Unsure of what may be causing it though, but it will spam the following in
some rooms with code objects

Woor'Tra (VCX-350 Freighter)               [(Invalid UTF8
code)�[38;5;3m(Invalid UTF8 code)�[38;5;100m(Invalid UTF8
code)�[38;5;142m(Invalid UTF8 code)�[38;5;11m(Invalid UTF8 code)�(Invalid
UTF8 code)�(Invalid UTF8 code)�[38;5;231m(Invalid UTF8 code)�[0m 100%]
[----offline----]

**Comment by BeipDev** [comment]
Ah yes, that's one I already knew about. All of the Pennmush servers blindly say they support UTF-8 but don't. BeipMU is just trusting what they say but they lie. So I'm adding in a new option to have BeipMU only negotiate the text encoding you've set:

Here's what that server says it supports when BeipMU connects to it: UTF-8;ISO-8859-1;US-ASCII;ASCII;x-penn-def

There's already a bug logged against Pennmush: https://github.com/pennmush/pennmush/issues/1352

But I'll still put in a workaround since servers are unlikely to update.. expect the workaround soon!

**Comment by lordbongos** [comment]
Thankee much sir!

**Comment by BeipDev** [comment]
Fixed in build 304, available now

**Comment by lordbongos** [comment]
That lock tik seems to have resolved that,  thankee sai!
