### ISSUE TITLE
Feature Request - Triggers - Script - Call with parameters

### ISSUE THREAD

**Issue by diamondmx** [BeipDev/BeipMU#174]
Allow the script to be passed parameters from the captured text either in addition to, or instead of, the full line matched.
Example:

**Trigger setup:**
(Fireball|Magic Missile)

**Script Call**
Name of the function to call: ShowSpell
Parameters to pass to the function: \1, "coreRulebook"

**Code**
function ShowSpell(window, line, spellName, rulebook)
{
  var spellUrl = "pathfinderwebsite/"+rulebook+"/"+spellname;
  // Navigate Browser to the URL
}

**Note**
The line is redundant here, so it could be left out, but it might sometimes be needed in addition.
Also, some people might want an array of matches instead of specific matches. Perhaps a \* option to supply all matches from \0 upwards as an array to the script.
Current workaround is to replicate the regex inside the function. But you can't reuse functions that way because the function needs to know the source regex.

**Comment by BeipDev** [comment]
Internally the match is an array of indices into the text, an array of begin/end ranges (the primary range first, and () captures following). Do you have any suggestions on how best to pass this to Javascript? Maybe with some specific examples I can make work also.

**Comment by diamondmx** [comment]
I'm not sure how you're interfacing with the JS side of things, so I can share thoughts on that if you show me the script-call code on the c++ side of things (though my c++ is rusty :) )

On the JS side:
Either being able to get a parameter that's an array of the actual match strings, or being able to get individual matches passed in in a similar way to how you're doing it for the Send tab would be ideal.

As referenced in my example above, my use case is being able to pass in one match from the trigger regex, and one literal string, so I'd want the JS function to be called with:
ShowSpell(
window - the same window param as before,
line - same as before - I don't need it but probably simplest just to leave it in,
spellName - the \1 match from the regex,
rulebook - the literal string "coreRulebook" provided by the trigger
)

Getting the actual text of the matches is much more easy for the user than the indices, so I'd get the substr before passing to JS.

Lemme know if this doesn't quite answer what you were asking.

**Comment by BeipDev** [comment]
The regex engine returns a list of ranges in the string that it found matches (which is the most flexible since if you want to recolor things you want to know where the match was, not what the match was). From the ranges you can easily get the strings, since you can just substr that range from the line of text. So the list of ranges being passed in should be the most powerful option and still be fairly easy.

For interfacing with the JS it's just telling the JS engine to call the function name you provide and I pass it an TextWindowLine object ( https://github.com/BeipDev/BeipMU/blob/master/Documentation/ScriptingAPI.md#textwindowline ). The scripting engine gives an IDispatch interface that I use, nothing magical there, just a standard way to call functions and pass parameters. It's very un-C++ like actually.

Not hard to just also pass the regex result ranges. I might have to do it as a single array of the indices, and you'd have to group them in pairs yourself. I'll provide an example once I get it working.

**Comment by diamondmx** [comment]
Yeah, I can work with that, thanks!

**Comment by BeipDev** [comment]
Fixed in latest version
