### ISSUE TITLE
Cannot copy alias folders to another profile.

### ISSUE THREAD

**Issue by bash550** [BeipDev/BeipMU#37]
I found a bug that doesn't allow me to copy different folders in the alias dialog to move to another profile. It works in the Triggers dialog though.

**Comment by BeipDev** [comment]
I looked into this and I can move the alias folders around fine, can you provide repro steps?

**Comment by BeipDev** [comment]
Wow, the copy stuff was even broken for triggers. I made it work for all dialogs it's in now, here's the change list item for it for build 276:

Fixed Triggers/Aliases/Keyboard Macros so that 'Copy' always works and copies into the right place (previously only worked in triggers and copied in the wrong order)
