### ISSUE TITLE
Feature: Text Grabbing/Fugue Edit

### ISSUE THREAD

**Issue by skewskewskew** [BeipDev/BeipMU#70]
Create a trigger that enables triggered text to be copied into the input window.

There's a common (and old) MU function known as "FugueEdit", wherein the client will detect a certain pattern (Most commonly: `FugueEdit > `) and capture all text after that pattern and copies it into the text input window.

Example:

I input into the game `desc/edit me` - The game will capture my description and send it back to me as `FugueEdit > My Description Here`. The trigger then copies `My Description Here` into the input window.

A general "place capture group into the input window" would also be broadly useful.

**Comment by BeipDev** [comment]
Check out the latest beta, I added a '/setinput' command and since the Send trigger will process commands you can use that to set the input field. Plus.. you can also make the text clickable and when you click it'll do whatever you put into the send box too. So... that should cover all possibilities!
